### ISSUE TITLE
Deep match is not working

### ISSUE THREAD

**Issue by bilby91** [microsoftly/BotTester#14]
I'm trying to make deepMatch work but I always get false positives.

I saw this https://github.com/microsoftly/BotTester/blob/master/test/BotTester.spec.ts#L185

If I change the user id in the test it always works. Not sure what is the problem. Have tried using chai-subset and I'm getting the same issue. Any ideas @microsoftly ?

**Comment by microsoftly** [comment]
That's interesting. I'll look into it. I found it a bit hard initially to find something that could do the deep matching well. 

What may be a better solution is to break down IMessage into each component (text, address, type, etc .... ) then check against each of those and throw an error when one of them doesn't match (if defined in the expectation). That would definitely give better error reporting too instead of a giant blob of red

**Comment by bilby91** [comment]
Yep, breaking the IMessage probably would be better but I think the deep match should be fine for the moment. The problem as I mentioned is that is not working correctly :(. Let me know if you find anything please!

**Comment by microsoftly** [comment]
@bilby91 fixed #16

**Comment by bilby91** [comment]
Awesome!

When you have a moment can you check on #15 ? 

Thanks

Martín Fernández

On Tue, Sep 05, 2017 at 9:18 PM Matthew Schwartz

<
mailto:Matthew Schwartz <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

https://github.com/bilby91
fixed
https://github.com/microsoftly/BotTester/pull/16

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/microsoftly/BotTester/issues/14#issuecomment-327338462
, or
