### ISSUE TITLE
message is missing address or serviceUrl

### ISSUE THREAD

**Issue by pezholio** [microsoftly/BotTester#50]
Hi,

I've been using BotTester to test my bot, and it seems to be working pretty well, however, BotBuilder keeps raising the error `ChatConnector: send - message is missing address or serviceUrl.`. It doesn't interfere with the running of my tests, but is a bit noisy. Any ideas where I might be going wrong? (p.s. Node is not my first language - I'm primarily a Rubyist)

```javascript
require('dotenv').config()

var _wastebot = require('../lib/bot');

var _botBuilder = require('botbuilder');
var _botTester = require('bot-tester');

var nock = require('nock');

const connector = new _botTester.TestConnector({
  defaultAddress: _botBuilder.IAddress
});

describe('bot', function() {
  let bot;
  let botTester;
  
  beforeEach(() => {
    bot = _wastebot._private.bot
    botTester = new _botTester.BotTester(bot)
  });
  
  it('sends a welcome message', () => {
    return botTester
      .sendMessageToBot('Hello!', 'Welcome to Wastebot.', 'What is your postcode?')
      .runTest();
  });
  
  it('only supports postcodes in Lichfield District', () => {
    nock('http://api.postcodes.io')
      .get('/postcodes/sw1a1aa')
      .reply(200, {
        result: {
          codes: {
            admin_district: 'hahajajaaak'
          }
        }
      })
    
    return botTester
      .sendMessageToBot('sw1a1aa', 'Sorry, this service is for residents of Lichfield District only')
      .runTest();
  });
  
  it('returns a list of addresses', () => {
    nock('http://api.postcodes.io')
      .get('/postcodes/sw1a1aa')
      .reply(200, {
        result: {
          codes: {
            admin_district: 'E07000194'
          }
        }
      })
    
    nock('https://api.getaddress.io')
      .get('/v2/uk/sw1a1aa')
      .query(true)
      .reply(200, {
        Addresses: [
          [
            '123 Test Road',
            '',
            '',
            'Testtown',
            'Testshire'
          ],
          [
            '125 Test Road',
            '',
            '',
            'Testtown',
            'Testshire'
          ]
        ]
      })
    
    return botTester
      .sendMessageToBot('Hello!', 'Welcome to Wastebot.', 'What is your postcode?')
      .sendMessageToBot('sw1a1aa', 'Choose your address from the list below (1. 123 Test Road, Testtown, Testshire or 2. 125 Test Road, Testtown, Testshire)')
      .runTest();
  });

});
```

**Comment by microsoftly** [comment]
This may be an issue on the package side. I'll look into it tonight. I think it has something to do with not having a default service uri in the default address. It shouldn't matter as far as this package is concerned because the channel dependencies are mocked (is my first thought)

**Comment by microsoftly** [comment]
# Summary
I think this is an issue with your implementation of your bot and or your tests. Your bot uses botbuilder's ChatConnector.

# details
While you create a Test Connector (from bot-tester), it is not used. The error message you're seeing is defined in the [ChatConnector](https://github.com/Microsoft/BotBuilder/blob/master/Node/core/src/bots/ChatConnector.ts#L281) provided by the botbuilder framework.

The BotTester framework should work fine regardless of the connector being used, but only with the TestConnector will you not see unwanted side effects (such as messaging to console/real service).

If you check your implementation of ```_wastebot```, I'd wager that you would find the connector initialization. If the message concerns you, then you can take one of the following paths:
* You want to keep file structure the same (I'd recommend this for smaller projects)
  * in ```lib/bot```, expose a function that returns a UniversalBot and takes a Connector as an argument. You should have a line of code that is equivalent to ```new UniversalBot(connector)```. Do all of your setup here (e.g. apply dialogs, rules, etc ...)
* You want to separate domain/concerns by file (I'd recommend this for larger projects)
  * Create 2 files.
    1. Rule/Dialog application. This file should expose a function that takes in as a parameter. The dialogs and all additional rules that need be set on a bot are applied here. You should NOT see a call to ```new UniversalBot(connector)```
      2. Bot initialization. This file should expose a function that returns a UniversalBot and takes a Connector as an argument. You should have a line of code that is equivalent to ```new UniversalBot(connector)```. 
  * When the bot is used/exposed elsewhere, import both functions from you've made. Take the bot created from the initializer and apply the dialog/rules function to it. This exported bot is then ready for use.

I personally favor the second approach because it is more testable and can scale better. Lmk if this help, have additional questions, or my analysis turns out to be incorrect. 

Because I believe I have found the source of this message, I am closing this issue.

**Comment by pezholio** [comment]
Awesome, thanks! Sorry for the delay in getting back to you, but that seems to be working perfectly. Thank you! 👍

**Comment by microsoftly** [comment]
@pezholio 

All good. Just so you know, I made a PR to the botbuilder repo to give better error reporting for the error you saw. ->

https://github.com/Microsoft/BotBuilder/pull/4061/files
